# Generated by Django 3.2.16 on 2023-01-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on', 'political_view', 'category']},
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('ECONOMY', 'Economy'), ('SPORTS', 'Sports')], default=0, max_length=20),
        ),
    ]
