# Generated by Django 3.2.16 on 2023-01-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20230114_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('ECONOMY', 'Economy'), ('SPORTS', 'Sports'), ('POLITICAL', 'Political')], default=0, max_length=20),
        ),
    ]
