# Generated by Django 3.2.16 on 2023-01-21 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on', 'political_view']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
